name: 'Lambda Deploy'

on:
  push:
    branches: [main]
    paths:
    - "backend/**"

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Package and update lambda
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/lambda_script.sh"
          "${GITHUB_WORKSPACE}/.github/lambda_script.sh"
        shell: bash


  # terraform:
  #   runs-on: ubuntu-latest
  #   needs: 
  #   - checkout
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v1

  #     - name: Terraform Init
  #       working-directory: backend/terraform/
  #       run: |
  #         terraform init \
  #           -backend-config "bucket=www.ayodele.cloud" \
  #           -backend-config "key=backend/terraform.tfstate"
  #         terraform workspace new dev || terraform workspace select dev
  #     - name: Terraform Format
  #       working-directory: backend/terraform/
  #       run: terraform fmt

  #     - name: Terraform Plan
  #       working-directory: backend/terraform/
  #       run: terraform plan -var="environment=development"

  #     - name: Terraform Apply
  #       working-directory: backend/terraform/
  #       run: terraform apply -var="environment=development" -auto-approve